package abiz.ir.demo2.exception;

public enum ApiExceptionType {

    USER_NOT_FOUND,
    USER_NAME_MUST_NOT_NULL,
    FIRST_NAME_MUST_NOT_NULL,
    LAST_NAME_MUST_NOT_NULL,
    PASSWORD_MUST_NOT_NULL,
    PASSWORD_INCORRECT_ERROR,

    USER_NAME_MIN_LENGTH,
    USER_NAME_MAX_LENGTH,

    FIRST_NAME_MIN_LENGTH,
    FIRST_NAME_MAX_LENGTH,

    LAST_NAME_MIN_LENGTH,
    LAST_NAME_MAX_LENGTH,

    PASSWORD_MIN_LENGTH,
    PASSWORD_MAX_LENGTH,
    USER_NAME_ALREADY_EXIST,
    USERS_LIST_IS_EMPTY

}
